### ISSUE TITLE
Minimize logs issue

### ISSUE THREAD

**Issue by angyalz** [electroflame/homebridge-cec-tv-control#2]
**Describe The Bug:**
I try to minimize logs by using checkbox, but this plugin generates also five entry per second

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: latest
* **Homebridge Version**: latest
* **Node.js Version**: 16
* **NPM Version**: 
* **Operating System**: raspbian

**Comment by electroflame** [comment]
What logs are you seeing?  Can you paste a snippet of your log so I can see what you're talking about?

Five logs per second seems excessive, and far exceeds what I normally see with verbose logging disabled.

**Comment by angyalz** [comment]
There's a snapshot from logs:![image](https://user-images.githubusercontent.com/73586136/139846968-46da9f0d-7c6e-490b-9bb5-fa6ec80b5d4b.jpeg)

**Comment by electroflame** [comment]
That looks like minimize logging is not enabled.  Can I see your config.json for the plugin?

**Comment by angyalz** [comment]
Yes of course:
```{
            "name": "Blaupunkt TV",
            "manufacturer": "Blaupunkt",
            "model": "40/138O-GB-11B4-FEGBQU-EU",
            "serial": "BB40A138BFN0U0E56M-xxxxx xxxxx",
            "pollingInterval": 2500,
            "minimizeLogging": true,
            "inputs": [
                {
                    "inputNumber": 1,
                    "displayName": "Apple TV"
                },
                {
                    "inputNumber": 2,
                    "displayName": "Raspberry Pi"
                },
                {
                    "inputNumber": 3,
                    "displayName": "Direct One Sat"
                }
            ],
            "useActiveSource": true,
            "useInactiveSource": true,
            "useSourceRouting": true,
            "useSetStreamPath": true,
            "platform": "TVCECControl"
        }```

**Comment by electroflame** [comment]
Ah, I see now.  You're currently running your Homebridge instance in Debug mode, so you're seeing some extra, debug-only logging (mainly from cec-client).  You're seeing the actual CEC Bus traffic in those logs, which explains why you get multiple per-second (basically requesting the status, getting the status back from the device, etc.).

You can deactivate Debug mode for your Homebridge instance and those will be hidden.  Alternatively, you can increase pollingInterval to something a bit higher (I've been keeping mine at 10000, or 10 seconds).  Right now you're polling the device every two and a half seconds, which will lead to quite a bit of logging with Debug mode enabled.

**Comment by angyalz** [comment]
Ohh sorry, you're right!
