### ISSUE TITLE
Cannot read properties of undefined (reading 'displayName')

### ISSUE THREAD

**Issue by albinmedoc** [electroflame/homebridge-cec-tv-control#3]
**Describe The Bug:**

I cant change the input, it worked for me earlier today, but i reinstalled the plugin and it stopped working. 

**To Reproduce:**

Change input

**Expected behavior:**

I expect the input to change to me desired input source.

**Logs:**

```
This plugin threw an error from the characteristic 'Active Identifier': Unhandled error thrown inside write handler for characteristic: Cannot read properties of undefined (reading 'displayName'). See https://homebridge.io/w/JtMGR for more info.
```

**Plugin Config:**

```json
{
            "name": "CEC",
            "manufacturer": "Samsung",
            "model": "N/A",
            "pollingInterval": 2500,
            "minimizeLogging": false,
            "inputs": [
                {
                    "inputNumber": 2,
                    "displayName": "Chromecast"
                },
                {
                    "inputNumber": 3,
                    "displayName": "Playstation"
                }
            ],
            "useActiveSource": true,
            "useInactiveSource": true,
            "useSourceRouting": true,
            "useSetStreamPath": true,
            "platform": "TVCECControl",
            "_bridge": {
                "username": "0E:DB:6A:2E:7E:94",
                "port": 58221
            }
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: v0.1.18
* **Homebridge Version**: v1.5.0
* **Node.js Version**: v16.15.1
* **NPM Version**: v6.14.12
* **Operating System**: Raspbian GNU/Linux Buster

**Comment by albinmedoc** [comment]
I found a solution. 
As you see in my configuration I have only added inputs for HDMI2 & HDMI3 and not for HDMI1 (raspberry pi).

When I updated my config to add HDMI1 it all worked fine. 

This should be mentioned in the README. I don´t know if its just because it´s the raspberry itself that was missing. Or if all active inputs must be defined....

**Comment by electroflame** [comment]
Interesting!  Thanks for the report.

It definitely looks like it's due to skipping over HDMI 1.  I don't think it's due to HDMI 1 being the Raspberry Pi, but rather that I was assuming that the HDMI inputs were sequential in the Inputs array.

I think it's a bit of a fringe case you've got here, and reworking things to allow random or non-sequential inputs is a bit too much work for a small plugin like this -- but I can definitely make a note in the Readme.

Thanks!  I'm glad you figured it out!
